# fly.toml app configuration file generated for langgraph-ebay-shopper-winter-forest-2206 on 2025-08-26T23:32:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langgraph-ebay-shopper-winter-forest-2206'
primary_region = 'iad'

[build]
  image = 'tafari995/ebay_shop_agent:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  handlers = ["http"]
  port = 8000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
